// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nleohhsbddqxhwolyczd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sZW9oaHNiZGRxeGh3b2x5Y3pkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MDk5NTAsImV4cCI6MjA2ODk4NTk1MH0.Gq-kVeFQ_rnhpacJJCr1Hm89QTz653FoUtKNyq1Y-zo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});